import './globals.css'
import { Inter } from 'next/font/google'
import { NavBar } from './components/navBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='backgroundImage min-h-screen w-full flex flex-col  space-y-[100px] pb-[20px]'>
        <NavBar />
        {
          children
        }
      </body>
      
    </html>
  )
}
